using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._RuMC14.Ordnance;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;

namespace Content.Client._RuMC14.Ordnance;

[GenerateTypedNameReferences]
public sealed partial class RuMCDemolitionsScannerWindow : FancyWindow
{
    public RuMCDemolitionsScannerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(RMCDemolitionsScannerBuiState state)
    {
        StatusLabel.Text = $"Scan complete: {state.CasingName}";
        StatusLabel.FontColorOverride = Color.FromHex("#9effb6");

        CasingLabel.Text = $"Casing: {state.CasingName}";
        StageLabel.Text = $"Assembly state: {GetStageText(state.Stage)}";
        DetonatorLabel.Text = $"Detonator: {(state.HasDetonator ? "installed" : "missing")}";
        VolumeLabel.Text = $"Chemicals: {(int) state.CurrentVolume}/{(int) state.MaxVolume}u";

        BlastLabel.SetMarkup(state.HasExplosion
            ? $"[color=#ffd37a]Projected blast:[/color] Power {(int) state.BlastPower}, falloff {(int) state.BlastFalloff}, approx. radius {state.BlastRadius:F1} tiles."
            : "[color=#7f8a99]No explosive payload detected.[/color]");

        FireLabel.SetMarkup(state.HasFire
            ? $"[color=#ff9d6b]Projected fire:[/color] Intensity {(int) state.FireIntensity}, radius {(int) state.FireRadius} tiles, duration {(int) state.FireDuration}s."
            : "[color=#7f8a99]No incendiary payload detected.[/color]");

        SummaryLabel.SetMarkup(BuildSummary(state));
    }

    private string BuildSummary(RMCDemolitionsScannerBuiState state)
    {
        var lines = new List<string>();

        if (!state.HasExplosion && !state.HasFire)
            lines.Add("[color=#7f8a99]Payload is chemically inert. No meaningful blast or fire effect is expected.[/color]");
        else
            lines.Add("[color=#9effb6]Reactive payload detected. Handle as live ordnance.[/color]");

        if (!state.HasDetonator)
            lines.Add("[color=#ffb36b]Trigger path incomplete: no detonator assembly is installed.[/color]");
        else if (state.Stage != RMCCasingAssemblyStage.Armed)
            lines.Add("[color=#ffd37a]Trigger path present, but the casing is not fully armed yet.[/color]");
        else
            lines.Add("[color=#ff7a7a]Casing is armed and has an active detonator. Treat as immediately dangerous.[/color]");

        if (state.HasExplosion)
            lines.Add($"Estimated lethal blast envelope reaches roughly {state.BlastRadius:F1} tiles from impact.");

        if (state.HasFire)
            lines.Add($"Incendiary spread may cover up to {(int) state.FireRadius} tiles for about {(int) state.FireDuration} seconds.");

        return string.Join('\n', lines);
    }

    private static string GetStageText(RMCCasingAssemblyStage stage)
    {
        return stage switch
        {
            RMCCasingAssemblyStage.Open => "Open",
            RMCCasingAssemblyStage.Sealed => "Sealed",
            RMCCasingAssemblyStage.Armed => "Armed",
            _ => stage.ToString(),
        };
    }
}
