using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._RuMC14.Ordnance;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Maths;

namespace Content.Client._RuMC14.Ordnance;

[GenerateTypedNameReferences]
public sealed partial class RuMCDemolitionsScannerWindow : FancyWindow
{
    public RuMCDemolitionsScannerWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(RMCDemolitionsScannerBuiState state)
    {
        StatusLabel.Text = Loc.GetString("rmc-demolitions-scanner-ui-status", ("name", state.CasingName));
        StatusLabel.FontColorOverride = Color.FromHex("#9effb6");

        CasingLabel.Text = Loc.GetString("rmc-demolitions-scanner-ui-casing", ("name", state.CasingName));
        StageLabel.Text = Loc.GetString("rmc-demolitions-scanner-ui-stage", ("stage", GetStageText(state.Stage)));
        DetonatorLabel.Text = Loc.GetString("rmc-demolitions-scanner-ui-detonator",
            ("status", state.HasDetonator
                ? Loc.GetString("rmc-demolitions-scanner-ui-detonator-present")
                : Loc.GetString("rmc-demolitions-scanner-ui-detonator-missing")));
        VolumeLabel.Text = Loc.GetString("rmc-demolitions-scanner-ui-volume",
            ("current", (int) state.CurrentVolume),
            ("max", (int) state.MaxVolume));

        BlastLabel.SetMarkup(state.HasExplosion
            ? Loc.GetString("rmc-demolitions-scanner-ui-blast-present",
                ("power", (int) state.BlastPower),
                ("falloff", (int) state.BlastFalloff),
                ("radius", state.BlastRadius.ToString("F1")))
            : Loc.GetString("rmc-demolitions-scanner-ui-blast-none"));

        FireLabel.SetMarkup(state.HasFire
            ? Loc.GetString("rmc-demolitions-scanner-ui-fire-present",
                ("intensity", (int) state.FireIntensity),
                ("radius", (int) state.FireRadius),
                ("duration", (int) state.FireDuration))
            : Loc.GetString("rmc-demolitions-scanner-ui-fire-none"));

        SummaryLabel.SetMarkup(BuildSummary(state));
    }

    private string BuildSummary(RMCDemolitionsScannerBuiState state)
    {
        var lines = new List<string>();

        if (!state.HasExplosion && !state.HasFire)
            lines.Add(Loc.GetString("rmc-demolitions-scanner-ui-summary-empty"));
        else
            lines.Add(Loc.GetString("rmc-demolitions-scanner-ui-summary-payload"));

        if (!state.HasDetonator)
            lines.Add(Loc.GetString("rmc-demolitions-scanner-ui-summary-no-detonator"));
        else if (state.Stage != RMCCasingAssemblyStage.Armed)
            lines.Add(Loc.GetString("rmc-demolitions-scanner-ui-summary-not-armed"));
        else
            lines.Add(Loc.GetString("rmc-demolitions-scanner-ui-summary-ready"));

        if (state.HasExplosion)
            lines.Add(Loc.GetString("rmc-demolitions-scanner-ui-summary-radius", ("radius", state.BlastRadius.ToString("F1"))));

        if (state.HasFire)
        {
            lines.Add(Loc.GetString("rmc-demolitions-scanner-ui-summary-fire",
                ("radius", (int) state.FireRadius),
                ("duration", (int) state.FireDuration)));
        }

        return string.Join('\n', lines);
    }

    private static string GetStageText(RMCCasingAssemblyStage stage)
    {
        return stage switch
        {
            RMCCasingAssemblyStage.Open => Loc.GetString("rmc-demolitions-scanner-ui-stage-open"),
            RMCCasingAssemblyStage.Sealed => Loc.GetString("rmc-demolitions-scanner-ui-stage-sealed"),
            RMCCasingAssemblyStage.Armed => Loc.GetString("rmc-demolitions-scanner-ui-stage-armed"),
            _ => stage.ToString(),
        };
    }
}
