using Content.Client.UserInterface.Controls;
using Content.Shared._RuMC14.Ordnance;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client._RuMC14.Ordnance;

[GenerateTypedNameReferences]
public sealed partial class RuMCExplosionSimulatorWindow : FancyWindow
{
    private const float ProcessingDurationSeconds = 120f;

    public Action<FrameEventArgs>? OnFrameUpdate;

    public RuMCExplosionSimulatorWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(RMCExplosionSimulatorBuiState state, float processingSecondsLeft)
    {
        var secondsLeft = Math.Max(0, (int) MathF.Ceiling(processingSecondsLeft));
        var targetProfile = GetTargetProfile(state.Target);

        HeaderLabel.Text = state.IsProcessing
            ? Loc.GetString("rmc-explosion-sim-ui-header-processing")
            : state.SimulationReady
                ? Loc.GetString("rmc-explosion-sim-ui-header-ready")
                : Loc.GetString("rmc-explosion-sim-ui-header-idle");
        HeaderLabel.FontColorOverride = state.IsProcessing
            ? Color.FromHex("#ffd37a")
            : state.SimulationReady
                ? Color.FromHex("#9effb6")
                : Color.FromHex("#d9e8ff");

        ProcessingBar.Value = state.IsProcessing
            ? Math.Clamp(1f - (processingSecondsLeft / ProcessingDurationSeconds), 0f, 1f)
            : state.SimulationReady
                ? 1f
                : 0f;
        ProcessingLabel.Text = state.IsProcessing
            ? Loc.GetString("rmc-explosion-sim-ui-processing-remaining", ("seconds", secondsLeft))
            : state.SimulationReady
                ? Loc.GetString("rmc-explosion-sim-ui-processing-complete")
                : Loc.GetString("rmc-explosion-sim-ui-standby");

        MarinesButton.Pressed = state.Target == RMCExplosionSimulatorTarget.Marines;
        SpecialForcesButton.Pressed = state.Target == RMCExplosionSimulatorTarget.SpecialForces;
        XenomorphsButton.Pressed = state.Target == RMCExplosionSimulatorTarget.Xenomorphs;

        SampleLabel.Text = state.HasSample
            ? Loc.GetString("rmc-explosion-sim-ui-sample-loaded", ("name", state.SampleName))
            : Loc.GetString("rmc-explosion-sim-ui-no-sample");
        SampleLabel.FontColorOverride = state.HasSample
            ? Color.FromHex("#d9e8ff")
            : Color.FromHex("#b8a27f");

        TargetNotesLabel.Text = targetProfile.Notes;
        TargetNotesLabel.FontColorOverride = Color.FromHex("#d9e8ff");
        ReadinessLabel.Text = BuildReadinessSummary(state, targetProfile.Summary);
        ReadinessLabel.FontColorOverride = GetReadinessColor(state);
        BlastLabel.Text = BuildBlastSummary(state);
        BlastLabel.FontColorOverride = state.HasExplosion
            ? Color.FromHex("#ffe0a6")
            : Color.FromHex("#7f8a99");
        FireLabel.Text = BuildFireSummary(state);
        FireLabel.FontColorOverride = state.HasFire
            ? Color.FromHex("#ffc1a0")
            : Color.FromHex("#7f8a99");
        StatusLabel.Text = BuildStatusSummary(state, targetProfile.Summary, secondsLeft);
        StatusLabel.FontColorOverride = GetStatusColor(state);

        SimulateButton.Disabled = state.IsProcessing || !state.HasSample;
        ReplayButton.Disabled = state.IsProcessing || !state.SimulationReady;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        OnFrameUpdate?.Invoke(args);
    }

    private static string BuildReadinessSummary(RMCExplosionSimulatorBuiState state, string targetSummary)
    {
        if (!state.HasSample)
        {
            return string.Join('\n',
                Loc.GetString("rmc-explosion-sim-ui-readiness-no-sample-line1"),
                Loc.GetString("rmc-explosion-sim-ui-readiness-no-sample-line2"));
        }

        if (state.IsProcessing)
        {
            return string.Join('\n',
                Loc.GetString("rmc-explosion-sim-ui-readiness-processing-line1"),
                Loc.GetString("rmc-explosion-sim-ui-readiness-processing-line2", ("target", targetSummary)));
        }

        if (state.SimulationReady)
        {
            return string.Join('\n',
                Loc.GetString("rmc-explosion-sim-ui-readiness-ready-line1"),
                Loc.GetString("rmc-explosion-sim-ui-readiness-ready-line2"));
        }

        return string.Join('\n',
            Loc.GetString("rmc-explosion-sim-ui-readiness-staged-line1"),
            Loc.GetString("rmc-explosion-sim-ui-readiness-staged-line2", ("target", targetSummary)));
    }

    private static string BuildBlastSummary(RMCExplosionSimulatorBuiState state)
    {
        if (!state.HasExplosion)
        {
            return string.Join('\n',
                Loc.GetString("rmc-explosion-sim-ui-blast-none-line1"),
                Loc.GetString("rmc-explosion-sim-ui-blast-none-line2"));
        }

        var radius = MathF.Sqrt(MathF.Max(1f, state.TotalIntensity) / MathF.Max(1.5f, state.IntensitySlope));
        return string.Join('\n',
            Loc.GetString("rmc-explosion-sim-ui-blast-present-line1", ("power", (int) state.TotalIntensity)),
            Loc.GetString("rmc-explosion-sim-ui-blast-present-line2", ("falloff", state.IntensitySlope.ToString("F1"))),
            Loc.GetString("rmc-explosion-sim-ui-blast-present-line3", ("peak", (int) state.MaxIntensity)),
            Loc.GetString("rmc-explosion-sim-ui-blast-present-line4", ("radius", radius.ToString("F1"))));
    }

    private static string BuildFireSummary(RMCExplosionSimulatorBuiState state)
    {
        if (!state.HasFire)
        {
            return string.Join('\n',
                Loc.GetString("rmc-explosion-sim-ui-fire-none-line1"),
                Loc.GetString("rmc-explosion-sim-ui-fire-none-line2"));
        }

        return string.Join('\n',
            Loc.GetString("rmc-explosion-sim-ui-fire-present-line1", ("intensity", (int) state.FireIntensity)),
            Loc.GetString("rmc-explosion-sim-ui-fire-present-line2", ("radius", (int) state.FireRadius)),
            Loc.GetString("rmc-explosion-sim-ui-fire-present-line3", ("duration", (int) state.FireDuration)));
    }

    private static string BuildStatusSummary(RMCExplosionSimulatorBuiState state, string targetSummary, int secondsLeft)
    {
        if (state.IsProcessing)
        {
            return string.Join('\n',
                Loc.GetString("rmc-explosion-sim-ui-status-processing-line1", ("target", targetSummary)),
                Loc.GetString("rmc-explosion-sim-ui-status-processing-line2", ("seconds", secondsLeft)));
        }

        if (!state.SimulationReady)
        {
            return string.Join('\n',
                Loc.GetString("rmc-explosion-sim-ui-status-idle-line1"),
                Loc.GetString("rmc-explosion-sim-ui-status-idle-line2"));
        }

        var radius = MathF.Sqrt(MathF.Max(1f, state.TotalIntensity) / MathF.Max(1.5f, state.IntensitySlope));
        var lines = new List<string>
        {
            Loc.GetString("rmc-explosion-sim-ui-status-ready-line1", ("target", targetSummary)),
            state.HasExplosion
                ? Loc.GetString("rmc-explosion-sim-ui-status-ready-blast", ("radius", radius.ToString("F1")))
                : Loc.GetString("rmc-explosion-sim-ui-status-ready-no-blast"),
            state.HasFire
                ? Loc.GetString("rmc-explosion-sim-ui-status-ready-fire",
                    ("radius", (int) state.FireRadius),
                    ("duration", (int) state.FireDuration))
                : Loc.GetString("rmc-explosion-sim-ui-status-ready-no-fire"),
            Loc.GetString("rmc-explosion-sim-ui-status-ready-replay")
        };

        return string.Join('\n', lines);
    }

    private static ExplosionTargetProfile GetTargetProfile(RMCExplosionSimulatorTarget target)
    {
        return target switch
        {
            RMCExplosionSimulatorTarget.Marines => new ExplosionTargetProfile(
                Loc.GetString("rmc-explosion-sim-ui-target-summary-marines"),
                string.Join('\n',
                    Loc.GetString("rmc-explosion-sim-ui-target-notes-marines-1"),
                    Loc.GetString("rmc-explosion-sim-ui-target-notes-marines-2"),
                    Loc.GetString("rmc-explosion-sim-ui-target-notes-marines-3"))),
            RMCExplosionSimulatorTarget.SpecialForces => new ExplosionTargetProfile(
                Loc.GetString("rmc-explosion-sim-ui-target-summary-special-forces"),
                string.Join('\n',
                    Loc.GetString("rmc-explosion-sim-ui-target-notes-special-forces-1"),
                    Loc.GetString("rmc-explosion-sim-ui-target-notes-special-forces-2"),
                    Loc.GetString("rmc-explosion-sim-ui-target-notes-special-forces-3"))),
            RMCExplosionSimulatorTarget.Xenomorphs => new ExplosionTargetProfile(
                Loc.GetString("rmc-explosion-sim-ui-target-summary-xenomorphs"),
                string.Join('\n',
                    Loc.GetString("rmc-explosion-sim-ui-target-notes-xenomorphs-1"),
                    Loc.GetString("rmc-explosion-sim-ui-target-notes-xenomorphs-2"),
                    Loc.GetString("rmc-explosion-sim-ui-target-notes-xenomorphs-3"),
                    Loc.GetString("rmc-explosion-sim-ui-target-notes-xenomorphs-4"))),
            _ => new ExplosionTargetProfile(
                Loc.GetString("rmc-explosion-sim-ui-target-summary-unknown"),
                Loc.GetString("rmc-explosion-sim-ui-target-notes-unknown")),
        };
    }

    private static Color GetReadinessColor(RMCExplosionSimulatorBuiState state)
    {
        if (!state.HasSample)
            return Color.FromHex("#ffb36b");

        if (state.IsProcessing)
            return Color.FromHex("#ffd37a");

        return state.SimulationReady
            ? Color.FromHex("#9effb6")
            : Color.FromHex("#8fa1b8");
    }

    private static Color GetStatusColor(RMCExplosionSimulatorBuiState state)
    {
        if (state.IsProcessing)
            return Color.FromHex("#ffd37a");

        return state.SimulationReady
            ? Color.FromHex("#9effb6")
            : Color.FromHex("#8fa1b8");
    }

    private readonly record struct ExplosionTargetProfile(string Summary, string Notes);
}
