using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared._RuMC14.Ordnance;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;

namespace Content.Client._RuMC14.Ordnance;

[GenerateTypedNameReferences]
public sealed partial class RuMCExplosionSimulatorWindow : FancyWindow
{
    private const float ProcessingDurationSeconds = 120f;

    public Action<FrameEventArgs>? OnFrameUpdate;

    public RuMCExplosionSimulatorWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(RMCExplosionSimulatorBuiState state, float processingSecondsLeft)
    {
        var secondsLeft = Math.Max(0, (int) MathF.Ceiling(processingSecondsLeft));
        var targetProfile = GetTargetProfile(state.Target);

        HeaderLabel.SetMarkup(state.IsProcessing
            ? "[font size=16][bold][color=#ffd37a]Chemical Analysis In Progress[/color][/bold][/font]"
            : state.SimulationReady
                ? "[font size=16][bold][color=#9effb6]Simulation Package Ready[/color][/bold][/font]"
                : "[font size=16][bold][color=#d9e8ff]Explosion Simulation Computer[/color][/bold][/font]");

        ProcessingBar.Value = state.IsProcessing
            ? Math.Clamp(1f - (processingSecondsLeft / ProcessingDurationSeconds), 0f, 1f)
            : state.SimulationReady
                ? 1f
                : 0f;
        ProcessingLabel.Text = state.IsProcessing
            ? $"{secondsLeft}s remaining"
            : state.SimulationReady
                ? "Analysis complete"
                : "Standby";

        MarinesButton.Pressed = state.Target == RMCExplosionSimulatorTarget.Marines;
        SpecialForcesButton.Pressed = state.Target == RMCExplosionSimulatorTarget.SpecialForces;
        XenomorphsButton.Pressed = state.Target == RMCExplosionSimulatorTarget.Xenomorphs;

        BeakerLabel.Text = state.HasBeaker
            ? "Chemical sample loaded into the analysis bay."
            : "No beaker sample inserted.";
        BeakerLabel.FontColorOverride = state.HasBeaker
            ? Color.FromHex("#d9e8ff")
            : Color.FromHex("#b8a27f");

        TargetNotesLabel.SetMarkup(targetProfile.Notes);
        ReadinessLabel.SetMarkup(BuildReadinessSummary(state, targetProfile.Summary));
        BlastLabel.SetMarkup(BuildBlastSummary(state));
        FireLabel.SetMarkup(BuildFireSummary(state));
        StatusLabel.SetMarkup(BuildStatusSummary(state, targetProfile.Summary, secondsLeft));

        SimulateButton.Disabled = state.IsProcessing || !state.HasBeaker;
        ReplayButton.Disabled = state.IsProcessing || !state.SimulationReady;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        OnFrameUpdate?.Invoke(args);
    }

    private static string BuildReadinessSummary(RMCExplosionSimulatorBuiState state, string targetSummary)
    {
        if (!state.HasBeaker)
            return "[color=#ffb36b]Insert a beaker to unlock the analysis cycle.[/color]";

        if (state.IsProcessing)
            return $"[color=#ffd37a]Sample is sealed and being profiled against the {targetSummary} formation.[/color]";

        if (state.SimulationReady)
            return "[color=#9effb6]Latest solution package is cached. Replay can be launched at any time.[/color]";

        return $"[color=#8fa1b8]Sample is staged. Run a full analysis to compare it against the {targetSummary} profile.[/color]";
    }

    private static string BuildBlastSummary(RMCExplosionSimulatorBuiState state)
    {
        if (!state.HasExplosion)
            return "[color=#7f8a99]No explosive output predicted from the current reagent mix.[/color]";

        var radius = MathF.Sqrt(MathF.Max(1f, state.TotalIntensity) / MathF.Max(1.5f, state.IntensitySlope));
        return $"[color=#ffd37a]Predicted blast:[/color] Power {(int) state.TotalIntensity}, falloff {state.IntensitySlope:F1}, peak intensity {(int) state.MaxIntensity}, effective radius about {radius:F1} tiles.";
    }

    private static string BuildFireSummary(RMCExplosionSimulatorBuiState state)
    {
        if (!state.HasFire)
            return "[color=#7f8a99]No sustained incendiary spread predicted.[/color]";

        return $"[color=#ff9d6b]Predicted fire:[/color] Intensity {(int) state.FireIntensity}, radius {(int) state.FireRadius} tiles, duration {(int) state.FireDuration} seconds.";
    }

    private static string BuildStatusSummary(RMCExplosionSimulatorBuiState state, string targetSummary, int secondsLeft)
    {
        if (state.IsProcessing)
            return $"[color=#ffd37a]Processing the loaded sample against the {targetSummary} formation.[/color]\nPlayback data will unlock in approximately {secondsLeft} seconds.";

        if (!state.SimulationReady)
            return "[color=#8fa1b8]Load a beaker sample, pick a target profile, and run the two-minute simulation cycle.[/color]";

        var lines = new List<string>
        {
            $"[color=#9effb6]Simulation complete for the {targetSummary} formation.[/color]",
            state.HasExplosion
                ? $"Blast envelope reaches roughly {MathF.Sqrt(MathF.Max(1f, state.TotalIntensity) / MathF.Max(1.5f, state.IntensitySlope)):F1} tiles from the epicenter."
                : "Mixture does not generate a meaningful blast wave.",
            state.HasFire
                ? $"Incendiary spread is projected to cover {(int) state.FireRadius} tiles for about {(int) state.FireDuration} seconds."
                : "No persistent fire spread is expected.",
            "Use Replay Chamber to spawn the chamber and watch the predicted detonation."
        };

        return string.Join('\n', lines);
    }

    private static ExplosionTargetProfile GetTargetProfile(RMCExplosionSimulatorTarget target)
    {
        return target switch
        {
            RMCExplosionSimulatorTarget.Marines => new ExplosionTargetProfile(
                "USCM marine squad",
                "[color=#d9e8ff][bold]Standard infantry spread.[/bold][/color]\nSeven dummies are staggered in a broad line to show casualty drop-off and fragment reach against a typical fireteam footprint."),
            RMCExplosionSimulatorTarget.SpecialForces => new ExplosionTargetProfile(
                "special forces breach stack",
                "[color=#d9e8ff][bold]Compact armored cluster.[/bold][/color]\nFive dummies are packed tighter to stress-test high-power breaching mixes and near-epicenter overkill."),
            RMCExplosionSimulatorTarget.Xenomorphs => new ExplosionTargetProfile(
                "xenomorph assault wave",
                "[color=#d9e8ff][bold]Dense organic rush.[/bold][/color]\nNine dummies are packed forward to expose short-range saturation, fire spread, and how quickly the blast falls off through a hive push."),
            _ => new ExplosionTargetProfile(
                "unknown profile",
                "[color=#7f8a99]No target profile loaded.[/color]"),
        };
    }

    private readonly record struct ExplosionTargetProfile(string Summary, string Notes);
}
