using Content.Client.UserInterface.Controls;
using Content.Shared._RuMC14.Ordnance.Signaler;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._RuMC14.Ordnance;
// TODO: Fix silly ui update issues
[GenerateTypedNameReferences]
public sealed partial class RuMCOrdnanceSignalerWindow : FancyWindow
{
    public event Action<string>? OnFrequencyChanged;

    private uint _lastFrequency = 1330;

    public RuMCOrdnanceSignalerWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        FrequencyLineEdit.OnTextEntered += e => OnFrequencyChanged?.Invoke(e.Text);
        FrequencyLineEdit.OnTextChanged += ValidateText;
        FrequencyLineEdit.OnFocusExit += e => OnFrequencyChanged?.Invoke(e.Text);
    }

    private void ValidateText(LineEdit.LineEditEventArgs args)
    {
        if (!uint.TryParse(args.Text, out uint frequency))
        {
            FrequencyLineEdit.SetText(_lastFrequency.ToString());
            return;
        }

        _lastFrequency = uint.Parse(args.Text);
    }

    public void Update(OrdnanceSignalerBoundUIState state)
    {
        if (state.Frequency.ToString() != FrequencyLineEdit.Text)
            FrequencyLineEdit.Text = state.Frequency.ToString();
    }
}

