using Content.Shared._CMU14.Yautja;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CMU14.Yautja;

[GenerateTypedNameReferences]
public sealed partial class YautjaMarkWindow : DefaultWindow
{
    public event Action? OnRefresh;
    public event Action<NetEntity, YautjaMarkKind, string?>? OnMark;
    public event Action<NetEntity, YautjaMarkKind>? OnUnmark;

    private readonly Dictionary<int, YautjaMarkPanelEntry> _entries = new();
    private ItemList.Item? _selectedItem;

    public YautjaMarkWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("cmu-yautja-mark-window-title");

        AddMarkKind(YautjaMarkKind.Prey);
        AddMarkKind(YautjaMarkKind.Honored);
        AddMarkKind(YautjaMarkKind.Dishonored);
        AddMarkKind(YautjaMarkKind.GearCarrier);
        AddMarkKind(YautjaMarkKind.Thrall);
        AddMarkKind(YautjaMarkKind.Student);
        AddMarkKind(YautjaMarkKind.Blooded);
        MarkKindOption.OnItemSelected += args => MarkKindOption.SelectId(args.Id);
        MarkKindOption.SelectId((int) YautjaMarkKind.Prey);
        RefreshButton.OnPressed += _ => OnRefresh?.Invoke();
        MarkButton.OnPressed += _ => SendMark(false);
        UnmarkButton.OnPressed += _ => SendMark(true);
        TargetList.OnItemSelected += args => _selectedItem = args.ItemList[args.ItemIndex];
        TargetList.OnItemDeselected += args =>
        {
            if (ReferenceEquals(_selectedItem, args.ItemList[args.ItemIndex]))
                _selectedItem = null;
        };
    }

    public void UpdateState(YautjaMarkPanelState state)
    {
        _selectedItem = null;
        TargetList.Clear();
        _entries.Clear();

        for (var i = 0; i < state.Entries.Count; i++)
        {
            var entry = state.Entries[i];
            var marks = entry.Marks.Count == 0
                ? Loc.GetString("cmu-yautja-mark-none")
                : GetMarkList(entry.Marks);

            TargetList.Add(new ItemList.Item(TargetList)
            {
                Text = $"{entry.Name} [{(entry.IsXeno ? Loc.GetString("cmu-yautja-target-xeno") : Loc.GetString("cmu-yautja-target-humanoid"))}] - {marks}",
                Metadata = i,
            });
            _entries[i] = entry;
        }
    }

    private void SendMark(bool remove)
    {
        if (_selectedItem == null)
            return;

        if (_selectedItem.Metadata is not int index || !_entries.TryGetValue(index, out var entry))
            return;

        var kind = (YautjaMarkKind) MarkKindOption.SelectedId;
        if (remove)
            OnUnmark?.Invoke(entry.Entity, kind);
        else
            OnMark?.Invoke(entry.Entity, kind, ReasonEdit.Text);
    }

    private void AddMarkKind(YautjaMarkKind kind)
    {
        MarkKindOption.AddItem(Loc.GetString(YautjaMarkSystem.GetMarkName(kind)), (int) kind);
    }

    private static string GetMarkList(List<YautjaMarkKind> marks)
    {
        var names = new string[marks.Count];
        for (var i = 0; i < marks.Count; i++)
        {
            names[i] = Loc.GetString(YautjaMarkSystem.GetMarkName(marks[i]));
        }

        return string.Join(", ", names);
    }
}
