using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CMU14.Yautja;

[GenerateTypedNameReferences]
public sealed partial class YautjaThrallMessageWindow : DefaultWindow
{
    public event Action<string>? OnSend;

    public YautjaThrallMessageWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("cmu-yautja-thrall-message-title");
        SendButton.OnPressed += _ => Send();
        MessageEdit.OnTextEntered += _ => Send();
    }

    private void Send()
    {
        var text = MessageEdit.Text;
        if (string.IsNullOrWhiteSpace(text))
            return;

        OnSend?.Invoke(text);
        MessageEdit.Text = string.Empty;
    }
}
