using Content.Shared.AU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.AU14.ColonyEconomy;

[GenerateTypedNameReferences]
public sealed partial class AdminConsoleWindow : DefaultWindow
{
    public AdminConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(AdminConsoleBuiState state)
    {
        ColonyBudgetLabel.Text = $"Colony Budget: ${state.ColonyBudget:F0}";
        CurrentTaxLabel.Text = $"Current Sales Tax: {state.SalesTaxPercent:F0}%";
        TaxInput.Text = $"{state.SalesTaxPercent:F0}";
        CurrentIncomeTaxLabel.Text = $"Current Income Tax: {state.IncomeTaxPercent:F0}%";
        IncomeTaxInput.Text = $"{state.IncomeTaxPercent:F0}";
        UpdateEconomyStatus(state.EconomyStatus);
    }

    private void UpdateEconomyStatus(EconomyStatusState econ)
    {
        EconomyStatusPanel.RemoveAllChildren();
        EconomyStatusPanel.AddChild(new Label { Text = $"Sales Tax: {econ.SalesTaxPercent:F0}%" });
        EconomyStatusPanel.AddChild(new Label { Text = $"Income Tax: {econ.IncomeTaxPercent:F0}%" });
        EconomyStatusPanel.AddChild(new Label { Text = $"Transit Tariff: {econ.TransitTariffPercent:F0}%" });

        if (econ.ActiveEmbargoes.Count > 0)
            EconomyStatusPanel.AddChild(new Label { Text = $"Active Embargoes: {string.Join(", ", econ.ActiveEmbargoes)}", StyleClasses = { "Caution" } });
        else
            EconomyStatusPanel.AddChild(new Label { Text = "Embargoes: None", StyleClasses = { "LabelSubText" } });

        if (econ.ActiveTradePacts.Count > 0)
            EconomyStatusPanel.AddChild(new Label { Text = $"Active Trade Pacts: {string.Join(", ", econ.ActiveTradePacts)}" });
        else
            EconomyStatusPanel.AddChild(new Label { Text = "Trade Pacts: None", StyleClasses = { "LabelSubText" } });
    }
}
