using Content.Shared.AU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client.AU14.ColonyEconomy;

[GenerateTypedNameReferences]
public sealed partial class AU14CashVendorWindow : FancyWindow
{
    public event Action<int>? OnBuyPressed;

    private AU14CashVendorBuiState? _lastState;
    private readonly IPrototypeManager _protoManager;

    public AU14CashVendorWindow()
    {
        RobustXamlLoader.Load(this);
        _protoManager = IoCManager.Resolve<IPrototypeManager>();
        SearchBar.OnTextChanged += _ => RefreshList();
    }

    public void UpdateState(AU14CashVendorBuiState state)
    {
        _lastState = state;
        InsertedCashLabel.Text = $"${state.InsertedCash:F0}";
        ReturnChangeBtn.Disabled = state.InsertedCash <= 0;
        TaxFooterLabel.Text = state.SalesTaxPercent > 0
            ? $"Sales Tax: {state.SalesTaxPercent:F0}%"
            : "No sales tax";
        RefreshList();
    }

    private void RefreshList()
    {
        ItemList.RemoveAllChildren();

        if (_lastState == null)
            return;

        var filter = SearchBar.Text?.Trim() ?? string.Empty;

        foreach (var item in _lastState.Items)
        {
            if (!string.IsNullOrEmpty(filter) &&
                !item.Name.Contains(filter, StringComparison.OrdinalIgnoreCase))
                continue;

            var row = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 4,
                HorizontalExpand = true
            };

            // Entity icon — only show if prototype exists
            if (_protoManager.HasIndex<EntityPrototype>(item.ItemProtoId))
            {
                var icon = new EntityPrototypeView
                {
                    MinSize = new System.Numerics.Vector2(32, 32),
                    VerticalAlignment = VAlignment.Center
                };
                icon.SetPrototype(item.ItemProtoId);
                row.AddChild(icon);
            }
            else
            {
                // Placeholder for missing prototype
                row.AddChild(new Robust.Client.UserInterface.Control { MinSize = new System.Numerics.Vector2(32, 32) });
            }

            // Name label
            var nameLabel = new Label
            {
                Text = item.Name,
                HorizontalExpand = true,
                ClipText = true,
                SizeFlagsStretchRatio = 3
            };

            // Price label
            var priceLabel = new Label
            {
                Text = $"${item.EffectivePrice}",
                MinWidth = 40,
                HorizontalAlignment = HAlignment.Right
            };

            // Buy button
            var buyBtn = new Button { Text = "Buy", MinWidth = 50 };
            var idxCopy = item.Index;
            buyBtn.Disabled = _lastState.InsertedCash < item.EffectivePrice;
            buyBtn.OnPressed += _ => OnBuyPressed?.Invoke(idxCopy);

            row.AddChild(nameLabel);
            row.AddChild(priceLabel);
            row.AddChild(buyBtn);
            ItemList.AddChild(row);
        }

        if (ItemList.ChildCount == 0)
            ItemList.AddChild(new Label { Text = "No items available." });
    }
}
