using Content.Shared.AU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.AU14.ColonyEconomy;

[GenerateTypedNameReferences]
public sealed partial class CorporateConsoleWindow : DefaultWindow
{
    public CorporateConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(CorporateConsoleBuiState state)
    {
        CorporateBudgetLabel.Text = $"Corporate Budget: ${state.CorporateBudget:F0}";
        CurrentTariffLabel.Text = $"Current Transit Tariff: {state.TransitTariffPercent:F0}%";
        TariffInput.Text = $"{state.TransitTariffPercent:F0}";

        var incomeTax = state.EconomyStatus.IncomeTaxPercent;
        WithdrawTaxNote.Text = incomeTax > 0
            ? $"Note: Withdrawals are subject to {incomeTax:F0}% income tax."
            : "No income tax on withdrawals.";

        UpdateEconomyStatus(state.EconomyStatus);
    }

    private void UpdateEconomyStatus(EconomyStatusState econ)
    {
        EconomyStatusPanel.RemoveAllChildren();
        EconomyStatusPanel.AddChild(new Label { Text = $"Sales Tax: {econ.SalesTaxPercent:F0}%" });
        EconomyStatusPanel.AddChild(new Label { Text = $"Income Tax: {econ.IncomeTaxPercent:F0}%" });
        EconomyStatusPanel.AddChild(new Label { Text = $"Transit Tariff: {econ.TransitTariffPercent:F0}%" });

        if (econ.ActiveEmbargoes.Count > 0)
            EconomyStatusPanel.AddChild(new Label { Text = $"Active Embargoes: {string.Join(", ", econ.ActiveEmbargoes)}", StyleClasses = { "Caution" } });
        else
            EconomyStatusPanel.AddChild(new Label { Text = "Embargoes: None", StyleClasses = { "LabelSubText" } });

        if (econ.ActiveTradePacts.Count > 0)
            EconomyStatusPanel.AddChild(new Label { Text = $"Active Trade Pacts: {string.Join(", ", econ.ActiveTradePacts)}" });
        else
            EconomyStatusPanel.AddChild(new Label { Text = "Trade Pacts: None", StyleClasses = { "LabelSubText" } });
    }
}
