- type: job
  parent: AU14JobPlatCoBase
  id: AU14JobGOVFORPlatCoCMBCIU
  name: Platoon Commander
  spawnMenuRoleName: Platoon Commander (CMBCIU)
  ranks:
    AU14RankCMBMarshal: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: Marine # RuMC edit
      Faction: govfor
    - type: UserIFF
      factions:
      - GOVFOR
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14govforhud.rsi
        state: govfor_platoonsergeant
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORPlatCoCMBCIU
    - type: Skills # RuMC edit
      preset: AU14SkillPresetPlatoonCommander
