- type: job
  parent: AU14JobSectionSergeantBase
  id: AU14JobGOVFORSectionSergeantCMBCIU
  name: Unit Leader
  ranks:
    AU14RankCMBChiefDeputy: []
  spawnMenuRoleName: Section Sergeant (CMBCIU)
  special:
  - !type:AddComponentSpecial
    components:
    - type: Marine # RuMC edit
      Faction: govfor
    - type: UserIFF
      factions:
      - GOVFOR
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14govforhud.rsi
        state: govfor_platoonsergeant
    - type: JobPrefix
      prefix: au14-job-prefix-AU14JobGOVFORSectionSergeantCMBCIU
    - type: Skills  # RuMC edit
      skills:
        RMCSkillConstruction: 2
        RMCSkillCqc: 1
        RMCSkillEndurance: 2
        RMCSkillEngineer: 3
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillIntel: 1
        RMCSkillJtac: 2
        RMCSkillLeadership: 1
        RMCSkillMedical: 1
        RMCSkillVehicles: 1
        RMCSkillPolice: 2

