using System.Linq;
using System.Text.RegularExpressions;
using Content.Shared.Corvax.TTS;
using Content.Shared.Preferences;
using Content.Shared.Humanoid;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Prototypes;

namespace Content.Client.Corvax.TTS;

[GenerateTypedNameReferences]
public sealed partial class TTSTab : Control
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public event Action<string>? OnVoiceSelected;
    public event Action<string>? OnPreviewRequested;

    private List<TTSVoicePrototype> _allVoices = new();
    private List<TTSVoicePrototype> _filteredVoices = new();
    private Dictionary<string, List<TTSVoicePrototype>> _categorizedVoices = new();
    private string? _selectedVoiceId;
    private string? _selectedCategory;

    private static readonly Regex CategoryRegex = new(@"^(.*?)\s*\(([^)]+)\)\s*$", RegexOptions.Compiled);

    public TTSTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        SearchEdit.OnTextChanged += OnSearchChanged;
    }

    /// <summary>
    /// Единственная точка загрузки голосов
    /// </summary>
    public void UpdateControls(HumanoidCharacterProfile? profile, Sex sex)
    {
        if (profile != null)
            _selectedVoiceId = profile.Voice;

        // 🔥 ВАЖНО: грузим ВСЕ голоса здесь
        _allVoices = _prototypeManager
            .EnumeratePrototypes<TTSVoicePrototype>()
            .Where(o => o.RoundStart && HumanoidCharacterProfile.CanHaveVoice(o, sex))
            .OrderBy(o => Loc.GetString(o.Name))
            .ToList();

        BuildCategories();
        UpdateResults();
    }

    private void BuildCategories()
    {
        _categorizedVoices.Clear();
        CategoriesContainer.RemoveAllChildren();

        foreach (var voice in _allVoices)
        {
            var name = Loc.GetString(voice.Name).ToLowerInvariant();

            var category = string.IsNullOrWhiteSpace(voice.Category)
                ? Loc.GetString("humanoid-profile-editor-voice-other")
                : voice.Category;

            var match = CategoryRegex.Match(name);
            if (match.Success)
                category = match.Groups[2].Value.Trim();

            if (!_categorizedVoices.TryGetValue(category, out var list))
            {
                list = new List<TTSVoicePrototype>();
                _categorizedVoices[category] = list;
            }

            list.Add(voice);
        }

        foreach (var category in _categorizedVoices.Keys.OrderBy(k => k))
        {
            var button = new Button
            {
                Text = category,
                ToolTip = Loc.GetString("humanoid-profile-editor-voice-category-tooltip", ("category", category)),
                HorizontalExpand = true,
            };

            button.OnPressed += _ =>
            {
                _selectedCategory = category;
                SearchEdit.Text = "";
                UpdateResults();
            };

            CategoriesContainer.AddChild(button);
        }
    }

    private void OnSearchChanged(LineEdit.LineEditEventArgs args)
    {
        _selectedCategory = null;
        UpdateResults();
    }

    private void UpdateResults()
    {
        VoicesGrid.RemoveAllChildren();
        _filteredVoices.Clear();

        var searchText = SearchEdit.Text?.ToLowerInvariant() ?? "";

        foreach (var voice in _allVoices)
        {
            var name = Loc.GetString(voice.Name).ToLowerInvariant();

            var matchesSearch =
                string.IsNullOrEmpty(searchText)
                || name.Contains(searchText)
                || voice.ID.ToLowerInvariant().Contains(searchText);

            var matchesCategory =
                string.IsNullOrEmpty(_selectedCategory)
                || voice.Category == _selectedCategory;

            if (matchesSearch && matchesCategory)
            {
                _filteredVoices.Add(voice);
            }
        }

        foreach (var voice in _filteredVoices)
        {
            var displayName = Loc.GetString(voice.Name);
            var canSelectVoice = CanUseVoice(voice);

            var container = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center
            };

            var selectButton = new Button
            {
                Text = displayName,
                ToolTip = canSelectVoice
                    ? voice.ID
                    : Loc.GetString("humanoid-profile-editor-voice-tooltip-sponsoronly"),
                HorizontalExpand = true,
                Disabled = !canSelectVoice,
                StyleClasses = { StyleNano.ButtonOpenRight }
            };

            if (voice.ID == _selectedVoiceId)
                selectButton.AddStyleClass(StyleBase.ButtonCaution);

            selectButton.OnPressed += _ =>
            {
                if (canSelectVoice)
                    OnVoiceSelected?.Invoke(voice.ID);
            };

            var previewButton = new Button
            {
                Text = Loc.GetString("humanoid-profile-editor-voice-play"),
                MinWidth = 30,
                ToolTip = Loc.GetString("humanoid-profile-editor-voice-tooltip-play"),
                StyleClasses = { StyleNano.ButtonOpenLeft }
            };

            previewButton.OnPressed += _ =>
            {
                OnPreviewRequested?.Invoke(voice.ID);
            };

            container.AddChild(selectButton);
            container.AddChild(previewButton);

            VoicesGrid.AddChild(container);
        }

        ResultsLabel.Text = Loc.GetString("humanoid-profile-editor-voice-match",
            ("filtered", _filteredVoices.Count),
            ("all", _allVoices.Count));
    }

    private bool CanUseVoice(TTSVoicePrototype voice)
    {
        return true; // оставлено без изменений (дебаг / без ограничений)
    }

    public void SetSelectedVoice(string voiceId)
    {
        _selectedVoiceId = voiceId;
        UpdateResults();
    }
}