using System.Linq;
using Content.Shared._RMC14.CrewTracker;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Localization;

namespace Content.Client._RMC14.CrewTracker;

[GenerateTypedNameReferences]
public sealed partial class RMCCrewPinpointerWindow : DefaultWindow
{
    private readonly ILocalizationManager _loc;

    private RMCCrewPinpointerBuiState? _state;
    private Action<NetEntity>? _onSelect;

    public event Action? RefreshPressed;
    public event Action? ClearPressed;
    public event Action? TogglePressed;
    public event Action<string>? FavoritePressed;

    public RMCCrewPinpointerWindow()
    {
        RobustXamlLoader.Load(this);
        _loc = IoCManager.Resolve<ILocalizationManager>();

        SearchLineEdit.OnTextChanged += _ => RefreshListing();
        RefreshButton.OnPressed += _ => RefreshPressed?.Invoke();
        ClearButton.OnPressed += _ => ClearPressed?.Invoke();
        ToggleButton.OnPressed += _ => TogglePressed?.Invoke();
    }

    public void Populate(RMCCrewPinpointerBuiState state, Action<NetEntity> onSelect)
    {
        _state = state;
        _onSelect = onSelect;

        StatusLabel.Text = state.TargetName == null
            ? Loc.GetString("rmc-crew-pinpointer-status-none")
            : Loc.GetString(
                state.IsActive ? "rmc-crew-pinpointer-status-active" : "rmc-crew-pinpointer-status-inactive",
                ("target", state.TargetName));

        ToggleButton.Text = Loc.GetString(state.IsActive
            ? "rmc-crew-pinpointer-toggle-off"
            : "rmc-crew-pinpointer-toggle-on");

        RefreshListing();
    }

    private void RefreshListing()
    {
        Listing.DisposeAllChildren();
        Listing.RemoveAllChildren();

        if (_state == null)
            return;

        var filter = SearchLineEdit.Text.Trim();
        var hasFilter = filter.Length > 0;
        var addedEntries = false;
        var favoriteEntries = _state.Sections
            .SelectMany(section => section.Entries)
            .Where(entry => entry.Favorite)
            .Where(entry => !hasFilter || entry.Entry.Name.Contains(filter, StringComparison.CurrentCultureIgnoreCase))
            .ToList();

        if (favoriteEntries.Count > 0)
        {
            AddSectionHeader(Loc.GetString("rmc-crew-pinpointer-favorites"));
            foreach (var entry in favoriteEntries)
            {
                AddEntry(entry);
                addedEntries = true;
            }
        }

        foreach (var section in _state.Sections)
        {
            var entries = hasFilter
                ? section.Entries.Where(entry =>
                    entry.Entry.Name.Contains(filter, StringComparison.CurrentCultureIgnoreCase)).ToList()
                : section.Entries;

            if (entries.Count == 0)
                continue;

            addedEntries = true;
            AddSectionHeader(_loc.TryGetString(section.Name, out var localized) ? localized : section.Name);

            foreach (var entry in entries)
            {
                AddEntry(entry);
            }
        }

        if (addedEntries)
            return;

        var emptyText = _state.Sections.Count == 0
            ? Loc.GetString("rmc-crew-pinpointer-no-crew")
            : Loc.GetString(hasFilter
                ? "rmc-crew-pinpointer-no-search-results"
                : "rmc-crew-pinpointer-no-crew");

        Listing.AddChild(new Label
        {
            Text = emptyText,
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 10, 0, 0),
        });
    }

    private void AddSectionHeader(string text)
    {
        var header = new Label
        {
            Text = text,
            Margin = new Thickness(0, 6, 0, 0),
        };
        header.AddStyleClass("LabelBig");
        Listing.AddChild(header);
    }

    private void AddEntry(RMCCrewPinpointerEntry entry)
    {
        var row = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 4,
        };

        var selectButton = new Button
        {
            HorizontalExpand = true,
            TextAlign = Label.AlignMode.Left,
            Text = $"{entry.Entry.Name} - {entry.Entry.JobTitle}",
        };

        var favoriteButton = new Button
        {
            MinWidth = 110,
            Text = Loc.GetString(entry.Favorite
                ? "rmc-crew-pinpointer-favorite-remove"
                : "rmc-crew-pinpointer-favorite-add"),
        };

        var target = entry.Target;
        selectButton.OnPressed += _ => _onSelect?.Invoke(target);
        favoriteButton.OnPressed += _ => FavoritePressed?.Invoke(entry.Entry.Name);

        row.AddChild(selectButton);
        row.AddChild(favoriteButton);
        Listing.AddChild(row);
    }
}
