using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CMU14.Medical.Surgery;

[GenerateTypedNameReferences]
public sealed partial class CMUSurgeryWindow : DefaultWindow
{
    public CMUSurgeryWindow()
    {
        RobustXamlLoader.Load(this);
        Title = "Surgery";
    }
}
