- type: rank
  id: AU14RankCMBProbDeputy
  name: Probationary Deputy
  prefix: Prob. Dep.

- type: rank
  id: AU14RankCMBDeputy
  name: Deputy
  prefix: Dep.

- type: rank
  id: AU14RankCMBSrDeputy
  name: Senior Deputy
  prefix: Sr. Dep.

- type: rank
  id: AU14RankCMBChiefDeputy
  name: Chief Deputy
  prefix: Chf. Dep.

- type: rank
  id: AU14RankCMBMarshal
  name: CMB Marshal
  prefix: Mrshl.

- type: rank
  id: AU14RankColonyAdministrator
  name: Administrator
  prefix: Admin.

- type: rank
  id: AU14RankColonySeniorAdministrator
  name: Senior Administrator
  prefix: Sr. Admin.

- type: rank
  id: AU14RankCWPSRangerTrainee
  name: Probationary Ranger
  prefix: Prob. Ranger

- type: rank
  id: AU14RankCWPSRanger
  name: Ranger
  prefix: Ranger

- type: rank
  id: AU14RankCWPSSeniorRanger
  name: Senior Ranger
  prefix: Sr. Ranger

- type: rank
  id: AU14RankNSPAConstable
  name: Constable
  prefix: Constable

- type: rank
  id: AU14RankNSPASeniorConstable
  name: Senior Constable
  prefix: Sr. Constable

- type: rank
  id: AU14RankNSPAInspector
  name: Inspector
  prefix: Insp.

# Scientists

- type: rank
  id: AU14RankScientistAssistant
  name: Assistant Professor
  prefix: Assist-Prof.

- type: rank
  id: AU14RankScientistAssociate
  name: Associate Professor
  prefix: Asso-Prof.

- type: rank
  id: AU14RankScientistProfessor
  name: Professor
  prefix: Prof.

# Commercial Pilots

- type: rank
  id: AU14RankFirstOfficer
  name: First Officer
  prefix: 1st Off.

- type: rank
  id: AU14RankSeniorFirstOfficer
  name: Senior First Officer
  prefix: Sen. 1st Off.

- type: rank
  id: AU14RankCaptain
  name: Captain
  prefix: Cpt.

- type: rank
  id: AU14RankFlightCaptain
  name: Flight Captain
  prefix: Flt. Cpt.

# Orbital Manager

- type: rank
  id: AU14RankOrbitalManager
  name: Manager
  prefix: Man.

- type: rank
  id: AU14RankSeniorOrbitalManager
  name: Senior Manager
  prefix: Sn. Man.

# Administrative Assistant

- type: rank
  id: AU14RankColonyAdminAssistant
  name: Assistant
  prefix: Assist.

- type: rank
  id: AU14RankColonySeniorAdminAssistant
  name: Senior Assistant
  prefix: Sn. Assist.

# Corporate Assistant

- type: rank
  id: AU14RankWYJuniorAssistant
  name: Junior Assistant
  prefix: Jr. Assist.

- type: rank
  id: AU14RankWYAssistant
  name: Assistant
  prefix: Assist.

- type: rank
  id: AU14RankWYSeniorAssistant
  name: Senior Assistant
  prefix: Sn. Assist.

# Ambassadors

- type: rank
  id: AU14RankAmbassador
  name: Ambassador
  prefix: Amb.


- type: rank
  id: AU14RankTWEAmbassador
  name: High Commisioner
  prefix: High Comm.
