- type: rank
  id: RMCRankSergeantMajor
  name: Сержант-майор
  prefix: Серж-майор
  paygrade: E9E

- type: rank
  id: RMCRankMasterGunnerySergeant
  name: Старший комендор-сержант
  prefix: Ст. Ком-серж
  paygrade: E9

- type: rank
  id: RMCRankFirstSergeant
  name: Первый сержант
  prefix: 1-ый серж.
  paygrade: E8E

- type: rank
  id: RMCRankMasterSergeant
  name: Мастер-сержант
  prefix: Маст-Серж
  paygrade: E8

- type: rank
  id: RMCRankGunnerySergeant
  name: Комендор-сержант
  prefix: Ком-серж.
  paygrade: E7

- type: rank
  id: RMCRankStaffSergeant
  name: Штаб-сержант
  prefix: Штаб-серж.
  paygrade: E6

- type: rank
  id: RMCRankSergeant
  name: Сержант
  prefix: Серж.
  paygrade: E5

- type: rank
  id: RMCRankCorporal
  name: Капрал
  prefix: Капр.
  paygrade: E4

- type: rank
  id: RMCRankLanceCorporal
  name: Младший капрал
  prefix: Мл. Капр.
  paygrade: E3

- type: rank
  id: RMCRankPrivateFirstClass
  name: Рядовой первого класса
  prefix: Ряд. 1 кл.
  paygrade: E2

- type: rank
  id: RMCRankPrivate
  name: Рядовой
  prefix: Ряд.
  paygrade: E1

- type: rank
  id: RMCRankRecruit
  name: Рекрут
  prefix: Рек.
  paygrade: E0
