- type: rank
  id: RMCRankMajorGeneral
  name: Генерал-майор
  prefix: Ген-майор
  paygrade: O8

- type: rank
  id: RMCRankBrigadierGeneral
  name: Бригадный генерал
  prefix: Бриг-ген.
  paygrade: O7

- type: rank
  id: RMCRankColonel
  name: Полковник
  prefix: Полк.
  paygrade: O6

- type: rank
  id: RMCRankLieutenantColonel
  name: Подполковник
  prefix: Подполк.
  paygrade: O5

- type: rank
  id: RMCRankMajor
  name: Майор
  prefix: Майор
  paygrade: O4

- type: rank
  id: RMCRankCaptain
  name: Капитан
  prefix: Кап.
  paygrade: O3

- type: rank
  id: RMCRankFirstLT
  name: Старший лейтенант
  prefix: Ст. лейт.
  paygrade: O2

- type: rank
  id: RMCRankSecondLT
  name: Лейтенант
  prefix: Лейт.
  paygrade: O1

- type: rank
  id: RMCRankChiefWarrantOfficer5
  name: Chief Warrant Officer 5
  prefix: CWarOff5.
  paygrade: W5

- type: rank
  id: RMCRankChiefWarrantOfficer4
  name: Chief Warrant Officer 4
  prefix: CWarOff4.
  paygrade: W4

- type: rank
  id: RMCRankChiefWarrantOfficer3
  name: Chief Warrant Officer 3
  prefix: CWarOff3.
  paygrade: W3

- type: rank
  id: RMCRankChiefWarrantOfficer
  name: Старший прапорщик
  prefix: Ст. прап.
  paygrade: O0-2

- type: rank
  id: RMCRankWarrantOfficer
  name: Прапорщик
  prefix: Прап.
  paygrade: O0-1
