using Content.Shared._CE.Trading.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.Trading;

[GenerateTypedNameReferences]
public sealed partial class CEBuyPositionControl : Control
{
    [Dependency] private readonly IPrototypeManager _proto = default!;

    public event Action<CETradingPositionPrototype>? OnSelect;

    private bool _active = false;

    public CEBuyPositionControl(CETradingPositionPrototype entry, bool active)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Button.OnPressed += _ => OnSelect?.Invoke(entry);
        _active = active;

        UpdateView(entry);
        UpdateColor();
    }

    private void UpdateColor()
    {
        if (_active)
            return;

        Button.ModulateSelfOverride = Color.FromHex("#1f2124");
    }

    private void UpdateView(CETradingPositionPrototype entry)
    {
        View.SetPrototype(entry.Service.GetTexture(_proto));
    }
}
