using Content.Client._CE.UserInterface;
using Content.Client._CE.Workbench;
using Content.Shared._CE.Trading.Prototypes;
using Content.Shared._CE.Trading.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._CE.Trading;

[GenerateTypedNameReferences]
public sealed partial class CESellingRequestControl : Control
{
    [Dependency] private readonly IPrototypeManager _proto = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;

    public event Action? OnSellAttempt;

    public CESellingRequestControl(ProtoId<CETradingRequestPrototype> request, bool active)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        if (!_proto.Resolve(request, out var indexedRequest))
            return;

        //Requirements
        ItemRequirements.RemoveAllChildren();
        foreach (var requirement in indexedRequest.Requirements)
        {
            ItemRequirements.AddChild(new CEWorkbenchRequirementControl(requirement));
        }

        //Coin reward
        PriceHolder.RemoveAllChildren();
        var tradingSys = _entityManager.System<CEClientTradingPlatformSystem>();
        var price = tradingSys.GetPrice(indexedRequest);
        PriceHolder.AddChild(new CEPriceControl(price ?? 10000));

        RequestButton.OnPressed += _ => OnSellAttempt?.Invoke();
        RequestButton.Disabled = !active;
    }
}
