using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._CE.UserInterface;

[GenerateTypedNameReferences]
public sealed partial class CEPriceControl : Control
{
    [Dependency] private readonly IEntityManager _entity = default!;

    public CEPriceControl(int price)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var sprite = _entity.System<SpriteSystem>();

        var rsiPath = new ResPath("_CE/Interface/Misc/coins.rsi");

        var total = price;

        var gp = total / 100;
        total %= 100;

        var sp = total / 10;
        total %= 10;

        var cp = total;

        CopperView.Texture = sprite.Frame0(new SpriteSpecifier.Rsi(rsiPath, "c"));
        CopperText.Text = cp.ToString();

        SilverView.Texture = sprite.Frame0(new SpriteSpecifier.Rsi(rsiPath, "s"));
        SilverText.Text = sp.ToString();

        GoldView.Texture = sprite.Frame0(new SpriteSpecifier.Rsi(rsiPath, "g"));
        GoldText.Text = gp.ToString();
    }
}
