- type: entity
  id: SpawnPointIAA
  parent: SpawnPointJobBase
  name: IAA
  components:
  - type: SpawnPoint
    job_id: IAA
  - type: Sprite
    layers:
      - state: green
      - state: lawyer

- type: jobIcon
  parent: JobIcon
  id: JobIconRFI
  icon:
    sprite: /Textures/Imperial/Interface/Misc/imperial_job_icons.rsi
    state: RFI

- type: job
  id: IAA
  name: job-name-iaa
  playTimeTracker: JobIAA
  requirements:
    - !type:RoleTimeRequirement
      role: JobLawyer
      time: 3600 #Imperial role timers
    - !type:RoleTimeRequirement
      role: JobWarden
      time: 7200 #Imperial role timers
  startingGear: RFIGear
  icon: "JobIconRFI"
  supervisors: job-supervisors-centcom
  canBeAntag: false
  access:
    - Service
    - Maintenance
    - Command
    - External
    - Lawyer
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  skills:
  - skillBotany
  - skillBaseMed
  - skillBaseConstraction

- type: startingGear
  id: RFIGear
  equipment:
    id: RFIPDA
    ears: ClothingHeadsetRFI

- type: playTimeTracker
  id: JobIAA
