ent-ClothingUniformRandom-desc = Generated by neural networks based on the latest fashion trends.
ent-ClothingRandomSpawner-name = random colorful costume
ent-ClothingUniformRandomArmless-name = colorful hands-free costume
ent-ClothingUniformRandomStandard-name = colorful costume
ent-ClothingUniformRandomBra-name = colorful bra
ent-ClothingUniformRandomShorts-name = colorful pants
ent-ClothingUniformRandomShirt-name = colorful costume
