- type: job
  parent: AU14JobSquadRiflemanBase
  id: AU14JobGOVFORSquadRiflemanRMC
  name: au14-job-name-govforsquadriflemanRMC
  spawnMenuRoleName: Rifleman (TWE RMC)
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMC_LanceCorporal:
      entity: AU14ChevronRMCLanceCorporal
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobGOVFORSquadRifleman
        time: 54000 # 15 hours
    RMC_Marine:
      entity: AU14ChevronRMCMarine
      requirements: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: Marine #RuMC edit
      Faction: govfor
    - type: UserIFF
      factions:
      - GOVFOR
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14govforhud.rsi
        state: govfor_background
    - type: Skills
      skills:
        RMCSkillEndurance: 1
        RMCSkillFirearms: 2
        RMCSkillConstruction: 2
        RMCSkillEngineer: 3
        RMCSkillFireman: 1
        RMCSkillVehicles: 1
        RMCSkillPolice: 1
