- type: job
  parent: AU14JobPlatOpBase
  id: AU14JobGOVFORPlatOpRMC
  name: au14-job-name-govforplatopRMC
  description: au14-job-description-govforplatop
  setPreference: true
  canBeAntag: false
  requirements:
  - !type:AgeRequirement
    requiredAge: 25
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  ranks:
    RMC_2Lieutenant: []
  startingGear: AU14GearGOVFORPlatOp
  dummyStartingGear: AU14GearGOVFORPlatOpDummy
  icon: "AU14JobIconOpsOfc"
  requireAdminNotify: true
  spawnMenuRoleName: Junior Officer (TWE RMC)
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforCommand
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      skills:
        RMCSkillCqc: 2
        RMCSkillConstruction: 2
        RMCSkillEndurance: 2
        RMCSkillEngineer: 2
        RMCSkillFirearms: 2
        RMCSkillFireman: 2
        RMCSkillIntel: 2
        RMCSkillJtac: 4
        RMCSkillLeadership: 3
        RMCSkillMedical: 3
        RMCSkillNavigations: 1
        RMCSkillOverwatch: 1
        RMCSkillPolice: 2
        RMCSkillPowerLoader: 2
        RMCSkillSurgery: 1
        RMCSkillVehicles: 1
    - type: JobPrefix
      prefix: au14-job-prefix-govforplatop
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
  hidden: true
