using System.Linq;
using Content.Shared.AU14.Ambassador;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.AU14.Ambassador;

[GenerateTypedNameReferences]
public sealed partial class AmbassadorThirdPartyWindow : DefaultWindow
{
    public event Action<string>? OnCallThirdParty;

    private List<string> _thirdPartyIds = new();
    private Dictionary<string, (string DisplayName, float Cost)> _thirdParties = new();
    private HashSet<string> _calledParties = new();

    public AmbassadorThirdPartyWindow()
    {
        RobustXamlLoader.Load(this);

        ThirdPartySelect.OnItemSelected += args =>
        {
            ThirdPartySelect.SelectId(args.Id);
            if (args.Id >= 0 && args.Id < _thirdPartyIds.Count)
            {
                var id = _thirdPartyIds[args.Id];
                if (_thirdParties.TryGetValue(id, out var info))
                {
                    CostLabel.Text = $"Cost: ${info.Cost:F0}";
                }
            }
        };

        CallBtn.OnPressed += _ =>
        {
            if (ThirdPartySelect.SelectedId >= 0 && ThirdPartySelect.SelectedId < _thirdPartyIds.Count)
            {
                var id = _thirdPartyIds[ThirdPartySelect.SelectedId];
                OnCallThirdParty?.Invoke(id);
                StatusLabel.Text = "Requesting support...";
            }
        };
    }

    public void UpdateState(AmbassadorThirdPartyBuiState s)
    {
        BudgetLabel.Text = $"Budget: ${s.Budget:F0}";

        // Check if the party list actually changed to avoid rebuilding and flickering
        var newIds = s.CallableParties.Keys.ToList();
        var changed = !_thirdPartyIds.SequenceEqual(newIds);

        _thirdParties = s.CallableParties;
        _calledParties = s.CalledParties;

        if (changed)
        {
            var previousSelectedId = ThirdPartySelect.SelectedId;
            string? previousSelectedKey = null;
            if (previousSelectedId >= 0 && previousSelectedId < _thirdPartyIds.Count)
                previousSelectedKey = _thirdPartyIds[previousSelectedId];

            _thirdPartyIds = newIds;
            ThirdPartySelect.Clear();

            if (_thirdPartyIds.Count == 0)
            {
                StatusLabel.Text = "No third parties available to call.";
                CallBtn.Disabled = true;
                CostLabel.Text = "Cost: N/A";
                return;
            }

            CallBtn.Disabled = false;
            StatusLabel.Text = "";

            for (int i = 0; i < _thirdPartyIds.Count; i++)
            {
                var id = _thirdPartyIds[i];
                var info = s.CallableParties[id];
                var label = _calledParties.Contains(id) ? $"{info.DisplayName} [CALLED]" : info.DisplayName;
                ThirdPartySelect.AddItem(label, i);
                ThirdPartySelect.SetItemDisabled(ThirdPartySelect.GetIdx(i), _calledParties.Contains(id));
            }

            // Restore previous selection if still valid, otherwise select first
            var restoreIdx = previousSelectedKey != null ? _thirdPartyIds.IndexOf(previousSelectedKey) : -1;
            var selectIdx = restoreIdx >= 0 ? restoreIdx : 0;
            ThirdPartySelect.SelectId(selectIdx);
            if (_thirdParties.TryGetValue(_thirdPartyIds[selectIdx], out var selectedInfo))
                CostLabel.Text = $"Cost: ${selectedInfo.Cost:F0}";
        }
        else
        {
            // Update disabled states without rebuilding
            for (int i = 0; i < _thirdPartyIds.Count; i++)
            {
                var id = _thirdPartyIds[i];
                ThirdPartySelect.SetItemDisabled(ThirdPartySelect.GetIdx(i), _calledParties.Contains(id));
            }

            // Just update the cost label for current selection
            if (ThirdPartySelect.SelectedId >= 0 && ThirdPartySelect.SelectedId < _thirdPartyIds.Count)
            {
                var id = _thirdPartyIds[ThirdPartySelect.SelectedId];
                if (_thirdParties.TryGetValue(id, out var info))
                    CostLabel.Text = $"Cost: ${info.Cost:F0}";
            }
        }

        // Disable call button if selected party already called
        if (ThirdPartySelect.SelectedId >= 0 && ThirdPartySelect.SelectedId < _thirdPartyIds.Count)
        {
            var selectedId = _thirdPartyIds[ThirdPartySelect.SelectedId];
            CallBtn.Disabled = _calledParties.Contains(selectedId);
        }
    }
}
