using Content.Shared.AU14.Ambassador;
using Content.Shared.AU14.ColonyEconomy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.AU14.Ambassador;

[GenerateTypedNameReferences]
public sealed partial class AmbassadorConsoleWindow : DefaultWindow
{
    public AmbassadorConsoleWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(AmbassadorConsoleBuiState s)
    {
        BudgetLabel.Text = $"Budget: ${s.Budget:F0}";
        FactionLabel.Text = $"Faction: {s.FactionName}";

        // Economy with prices
        EmbargoStatus.Text = s.EmbargoActive
            ? $"[ACTIVE] Embargo: -20% submission payouts (${s.EmbargoCostPerMinute:F0}/min)"
            : $"Embargo: Inactive (${s.EmbargoCostPerMinute:F0}/min)";
        TradePactStatus.Text = s.TradePactActive
            ? $"[ACTIVE] Trade Pact: +20% submission payouts (${s.TradePactCostPerMinute:F0}/min)"
            : $"Trade Pact: Inactive (${s.TradePactCostPerMinute:F0}/min)";

        // Comms jam with price
        CommsJamStatus.Text = s.CommsJamActive
            ? $"[ACTIVE] Comms Jammed - All radio blocked (${s.CommsJamCostPerMinute:F0}/min)"
            : $"Comms: Normal (${s.CommsJamCostPerMinute:F0}/min)";

        // Broadcast cost
        BroadcastCostLabel.Text = $"Broadcast cost: ${s.BroadcastCost:F0} per message";

        // Signal with prices
        var signalText = $"Signal: Normal";
        if (s.SignalBoostActive) signalText = $"[ACTIVE] Signal Boost - Third parties arrive faster (${s.SignalBoostCostPerMinute:F0}/min)";
        else if (s.SignalJamActive) signalText = $"[ACTIVE] Signal Jam - Third parties arrive slower (${s.SignalJamCostPerMinute:F0}/min)";
        else signalText = $"Signal: Normal (Boost: ${s.SignalBoostCostPerMinute:F0}/min | Jam: ${s.SignalJamCostPerMinute:F0}/min)";
        SignalStatus.Text = signalText;

        // Radar scan button with price
        ScanRadarBtn.Text = $"Scan Radar (${s.RadarScanCost:F0})";

        // Economy status
        UpdateEconomyStatus(s.EconomyStatus);

        // Update radar list
        RadarList.RemoveAllChildren();
        if (s.RadarList.Count == 0)
        {
            RadarList.AddChild(new Label { Text = "No scan data. Press 'Scan Radar' to detect incoming shuttles." });
        }
        else
        {
            foreach (var name in s.RadarList)
            {
                RadarList.AddChild(new Label { Text = $"• {name}" });
            }
        }
    }

    private void UpdateEconomyStatus(EconomyStatusState econ)
    {
        EconomyStatusPanel.RemoveAllChildren();
        EconomyStatusPanel.AddChild(new Label { Text = $"Sales Tax: {econ.SalesTaxPercent:F0}%" });
        EconomyStatusPanel.AddChild(new Label { Text = $"Income Tax: {econ.IncomeTaxPercent:F0}%" });
        EconomyStatusPanel.AddChild(new Label { Text = $"Transit Tariff: {econ.TransitTariffPercent:F0}%" });

        if (econ.ActiveEmbargoes.Count > 0)
            EconomyStatusPanel.AddChild(new Label { Text = $"Active Embargoes: {string.Join(", ", econ.ActiveEmbargoes)}", StyleClasses = { "Caution" } });
        else
            EconomyStatusPanel.AddChild(new Label { Text = "Embargoes: None", StyleClasses = { "LabelSubText" } });

        if (econ.ActiveTradePacts.Count > 0)
            EconomyStatusPanel.AddChild(new Label { Text = $"Active Trade Pacts: {string.Join(", ", econ.ActiveTradePacts)}" });
        else
            EconomyStatusPanel.AddChild(new Label { Text = "Trade Pacts: None", StyleClasses = { "LabelSubText" } });
    }
}
