- type: loadout
  id: CivilianWorkwearYellowAU14
  equipment:
    jumpsuit: AU14CivilianWorkwearYellow

- type: loadout
  id: CivilianWorkwearPinkAU14
  equipment:
    jumpsuit: AU14CivilianWorkwearPink

- type: loadout
  id: CivilianWorkwearBlueAU14
  equipment:
    jumpsuit: AU14CivilianWorkwearBlue

- type: loadout
  id: CivilianWorkwearGreenAU14
  equipment:
    jumpsuit: AU14CivilianWorkwearGreen

- type: loadout
  id: JumpsuitDutchBandolierAU14
  equipment:
    jumpsuit: RMCJumpsuitDutchBandolier

- type: loadout
  id: JumpsuitCivilianAU14
  equipment:
    jumpsuit: RMCJumpsuitCivilian

- type: loadout
  id: JumpsuitColonistAU14
  equipment:
    jumpsuit: CMJumpsuitColonist

- type: loadout
  id: JumpsuitTShirtWhiteAU14
  equipment:
    jumpsuit: CMJumpsuitTShirtWhite

- type: loadout
  id: JumpsuitTShirtGrayAU14
  equipment:
    jumpsuit: CMJumpsuitTShirtGray

- type: loadout
  id: JumpsuitTShirtRedAU14
  equipment:
    jumpsuit: CMJumpsuitTShirtRed

- type: loadout
  id: HazardVestAU14
  equipment:
    jumpsuit: RMCHazardVest

- type: loadout
  id: CivilianWeYuEngineerClothesAU14
  equipment:
    jumpsuit: AU14CivilianWeYuEngineerClothes

- type: loadout
  id: CivilianParamedicClothesRedAU14
  equipment:
    jumpsuit: AU14CivilianParamedicClothesRed

- type: loadout
  id: CivilianParamedicClothesGreenAU14
  equipment:
    jumpsuit: AU14CivilianParamedicClothesGreen

- type: loadout
  id: USASFFatiguesAU14
  equipment:
    jumpsuit: AU14UASFFatigues

- type: loadout
  id: FormalWhiteServiceAU14
  equipment:
    jumpsuit: RMCJumsuitWhiteService

- type: loadout
  id: CMJumpsuitXOFormalAU14
  equipment:
    jumpsuit: CMJumpsuitXOFormal

- type: loadout
  id: ArmyJumpsuitAU14
  equipment:
    jumpsuit: AU14ArmyJumpsuit

- type: loadout
  id: ArmyJumpsuitTankerAU14
  equipment:
    jumpsuit: AU14ArmyJumpsuitTanker

- type: loadout
  id: JungleFatiguesAU14
  equipment:
    jumpsuit: AU14JungleFatigues

- type: loadout
  id: CCAFUniformAU14
  equipment:
    jumpsuit: AU14CCAFUniform
